version: '3'

services:
  kafka-nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nodejs
    container_name: kafka-nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "3030:3030"
    volumes:
      - .:/src
      - node_modules:/node_modules
    command: /node_modules/.bin/nodemon index.js
    networks:
      - laradock_backend

volumes:
  node_modules:

networks:    
  laradock_backend:
    external: true